---
# Additional Services Deployment Manifest
# OpenPolicy Platform - Additional Services

# Database Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-service
  namespace: openpolicy-platform
  labels:
    app: database-service
    tier: infrastructure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database-service
  template:
    metadata:
      labels:
        app: database-service
        tier: infrastructure
    spec:
      containers:
      - name: database-service
        image: openpolicy/database-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9015
        env:
        - name: SERVICE_PORT
          value: "9015"
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: openpolicy-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: openpolicy-config
              key: REDIS_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9015
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9015
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: openpolicy-platform
  labels:
    app: database-service
    tier: infrastructure
spec:
  type: ClusterIP
  ports:
  - port: 9015
    targetPort: 9015
    protocol: TCP
    name: http
  selector:
    app: database-service

---
# Cache Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-service
  namespace: openpolicy-platform
  labels:
    app: cache-service
    tier: infrastructure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cache-service
  template:
    metadata:
      labels:
        app: cache-service
        tier: infrastructure
    spec:
      containers:
      - name: cache-service
        image: openpolicy/cache-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9016
        env:
        - name: SERVICE_PORT
          value: "9016"
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: openpolicy-config
              key: REDIS_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9016
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9016
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cache-service
  namespace: openpolicy-platform
  labels:
    app: cache-service
    tier: infrastructure
spec:
  type: ClusterIP
  ports:
  - port: 9016
    targetPort: 9016
    protocol: TCP
    name: http
  selector:
    app: cache-service

---
# Queue Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-service
  namespace: openpolicy-platform
  labels:
    app: queue-service
    tier: infrastructure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: queue-service
  template:
    metadata:
      labels:
        app: queue-service
        tier: infrastructure
    spec:
      containers:
      - name: queue-service
        image: openpolicy/queue-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9017
        env:
        - name: SERVICE_PORT
          value: "9017"
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: openpolicy-config
              key: RABBITMQ_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9017
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9017
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: queue-service
  namespace: openpolicy-platform
  labels:
    app: queue-service
    tier: infrastructure
spec:
  type: ClusterIP
  ports:
  - port: 9017
    targetPort: 9017
    protocol: TCP
    name: http
  selector:
    app: queue-service

---
# Storage Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
  namespace: openpolicy-platform
  labels:
    app: storage-service
    tier: infrastructure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage-service
  template:
    metadata:
      labels:
        app: storage-service
        tier: infrastructure
    spec:
      containers:
      - name: storage-service
        image: openpolicy/storage-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9009
        env:
        - name: SERVICE_PORT
          value: "9009"
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: openpolicy-config
              key: DATABASE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9009
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9009
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: storage-service
  namespace: openpolicy-platform
  labels:
    app: storage-service
    tier: infrastructure
spec:
  type: ClusterIP
  ports:
  - port: 9009
    targetPort: 9009
    protocol: TCP
    name: http
  selector:
    app: storage-service

---
# Monitoring Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-service
  namespace: openpolicy-platform
  labels:
    app: monitoring-service
    tier: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring-service
  template:
    metadata:
      labels:
        app: monitoring-service
        tier: monitoring
    spec:
      containers:
      - name: monitoring-service
        image: openpolicy/monitoring-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9010
        env:
        - name: SERVICE_PORT
          value: "9010"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9010
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9010
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: openpolicy-platform
  labels:
    app: monitoring-service
    tier: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 9010
    targetPort: 9010
    protocol: TCP
    name: http
  selector:
    app: monitoring-service

---
# Analytics Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: openpolicy-platform
  labels:
    app: analytics-service
    tier: business
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
        tier: business
    spec:
      containers:
      - name: analytics-service
        image: openpolicy/analytics-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9011
        env:
        - name: SERVICE_PORT
          value: "9011"
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: openpolicy-config
              key: DATABASE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9011
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9011
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: openpolicy-platform
  labels:
    app: analytics-service
    tier: business
spec:
  type: ClusterIP
  ports:
  - port: 9011
    targetPort: 9011
    protocol: TCP
    name: http
  selector:
    app: analytics-service

---
# Audit Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  namespace: openpolicy-platform
  labels:
    app: audit-service
    tier: business
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
        tier: business
    spec:
      containers:
      - name: audit-service
        image: openpolicy/audit-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9012
        env:
        - name: SERVICE_PORT
          value: "9012"
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: openpolicy-config
              key: DATABASE_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9012
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9012
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: audit-service
  namespace: openpolicy-platform
  labels:
    app: audit-service
    tier: business
spec:
  type: ClusterIP
  ports:
  - port: 9012
    targetPort: 9012
    protocol: TCP
    name: http
  selector:
    app: audit-service

---
# OPA Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-service
  namespace: openpolicy-platform
  labels:
    app: opa-service
    tier: business
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opa-service
  template:
    metadata:
      labels:
        app: opa-service
        tier: business
    spec:
      containers:
      - name: opa-service
        image: openpolicy/opa-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9013
        env:
        - name: SERVICE_PORT
          value: "9013"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9013
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9013
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: opa-service
  namespace: openpolicy-platform
  labels:
    app: opa-service
    tier: business
spec:
  type: ClusterIP
  ports:
  - port: 9013
    targetPort: 9013
    protocol: TCP
    name: http
  selector:
    app: opa-service

---
# MCP Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-service
  namespace: openpolicy-platform
  labels:
    app: mcp-service
    tier: business
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcp-service
  template:
    metadata:
      labels:
        app: mcp-service
        tier: business
    spec:
      containers:
      - name: mcp-service
        image: openpolicy/mcp-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9014
        env:
        - name: SERVICE_PORT
          value: "9014"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9014
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9014
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-service
  namespace: openpolicy-platform
  labels:
    app: mcp-service
    tier: business
spec:
  type: ClusterIP
  ports:
  - port: 9014
    targetPort: 9014
    protocol: TCP
    name: http
  selector:
    app: mcp-service

---
# OP Import Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: op-import
  namespace: openpolicy-platform
  labels:
    app: op-import
    tier: business
spec:
  replicas: 2
  selector:
    matchLabels:
      app: op-import
  template:
    metadata:
      labels:
        app: op-import
        tier: business
    spec:
      containers:
      - name: op-import
        image: openpolicy/op-import:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9015
        env:
        - name: SERVICE_PORT
          value: "9015"
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: openpolicy-config
              key: DATABASE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9015
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9015
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: op-import
  namespace: openpolicy-platform
  labels:
    app: op-import
    tier: business
spec:
  type: ClusterIP
  ports:
  - port: 9015
    targetPort: 9015
    protocol: TCP
    name: http
  selector:
    app: op-import

---
# Scraper Service - Standardized Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-service
  namespace: openpolicy-platform
  labels:
    app: scraper-service
    tier: infrastructure
    version: "2.0.0"
    mode: "production"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scraper-service
      version: "2.0.0"
  template:
    metadata:
      labels:
        app: scraper-service
        tier: infrastructure
        version: "2.0.0"
        mode: "production"
    spec:
      containers:
      - name: scraper-service
        image: openpolicy/scraper-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9016
        env:
        # Standardized Service Configuration
        - name: SERVICE_PORT
          value: "9016"
        - name: HOST
          value: "0.0.0.0"
        - name: DEBUG
          value: "false"
        
        # Dual Database Configuration
        - name: SCRAPER_MODE
          value: "prod"
        - name: TEST_DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: openpolicy-config
              key: TEST_DATABASE_URL
        - name: PROD_DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: openpolicy-config
              key: PROD_DATABASE_URL
        
        # Standardized External Service URLs
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: openpolicy-config
              key: REDIS_URL
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: openpolicy-config
              key: RABBITMQ_URL
        
        # Performance Optimization Flags
        - name: ENABLE_CONNECTION_POOLING
          value: "true"
        - name: ENABLE_QUERY_CACHING
          value: "true"
        - name: ENABLE_BATCH_PROCESSING
          value: "true"
        - name: ENABLE_ASYNC_PROCESSING
          value: "true"
        
        # Standardized Scraper Configuration
        - name: MAX_CONCURRENT_SCRAPERS
          value: "20"
        - name: BATCH_SIZE
          value: "2000"
        - name: RATE_LIMIT_PER_MINUTE
          value: "120"
        - name: SCRAPER_TIMEOUT
          value: "180"
        - name: PROCESSING_TIMEOUT
          value: "300"
        - name: RETRY_ATTEMPTS
          value: "2"
        
        # Standardized Logging and Monitoring
        - name: LOG_LEVEL
          value: "INFO"
        - name: LOG_FORMAT
          value: "json"
        - name: METRICS_ENABLED
          value: "true"
        - name: PROMETHEUS_PORT
          value: "9090"
        
        # Standardized Health Check Configuration
        - name: HEALTH_CHECK_INTERVAL
          value: "30"
        - name: HEALTH_CHECK_TIMEOUT
          value: "10"
        
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9016
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9016
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: scraper-service
  namespace: openpolicy-platform
  labels:
    app: scraper-service
    tier: infrastructure
    version: "2.0.0"
    mode: "production"
spec:
  type: ClusterIP
  ports:
  - port: 9016
    targetPort: 9016
    protocol: TCP
    name: http
  selector:
    app: scraper-service
    version: "2.0.0"
