apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl
spec:
  replicas: 1
  selector: { matchLabels: { app: etl } }
  template:
    metadata: { labels: { app: etl } }
    spec:
      containers:
        - name: etl
          image: ghcr.io/your-org/etl:dev
          ports: [{ containerPort: 8090 }]
          env:
            - name: ETL_PORT
              valueFrom:
                configMapKeyRef: { name: openpolicy-config, key: ETL_PORT }
          readinessProbe:
            httpGet: { path: /readyz, port: 8090 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 8090 }
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: etl
spec:
  selector: { app: etl }
  ports:
    - name: http
      port: 80
      targetPort: 8090
