apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openpolicy-stg
resources:
  - namespace.yaml
  - api-gateway.yaml
  - etl.yaml
  - web.yaml
  - admin.yaml
  - scraper.yaml
  - policy.yaml
  - search.yaml
  - auth.yaml
  - postgres.yaml
configMapGenerator:
  - name: openpolicy-config
    literals:
      - API_GATEWAY_PORT=8080
      - ETL_PORT=8003
      - WEB_PORT=3000
      - ADMIN_PORT=3001
      - SCRAPER_PORT=8005
      - POLICY_PORT=8011
      - SEARCH_PORT=8010
      - AUTH_PORT=8009
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=openpolicy
      - POSTGRES_USER=postgres
      - ENVIRONMENT=staging
generatorOptions:
  disableNameSuffixHash: true
