apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openpolicy
resources:
  - namespace.yaml
  - api-gateway.yaml
  - etl.yaml
  - web.yaml
  - admin.yaml
  - scraper.yaml
  - policy.yaml
  - search.yaml
  - auth.yaml
  - notifications.yaml
  - config.yaml
  - health.yaml
  - monitoring.yaml
  - postgres.yaml
  - ingress.yaml
  - monitoring-stack.yaml
configMapGenerator:
  - name: openpolicy-config
    literals:
      - API_GATEWAY_PORT=8080
      - ETL_PORT=8003
      - WEB_PORT=3000
      - ADMIN_PORT=3001
      - SCRAPER_PORT=8005
      - POLICY_PORT=8011
      - SEARCH_PORT=8010
      - AUTH_PORT=8009
      - NOTIFICATIONS_PORT=8012
      - CONFIG_PORT=8013
      - HEALTH_PORT=8007
      - MONITORING_PORT=8015
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=openpolicy
      - POSTGRES_USER=postgres
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - METRICS_ENABLED=true
      - TRACING_ENABLED=true
generatorOptions:
  disableNameSuffixHash: true
